### PR TITLE
fix(beacon-node): apply tsgo cast + add slot to merged-in #9479 test emit

### PR DESCRIPTION
**Pull request by lodekeeper**
## Summary

The base-branch update brought in #9479's new test ("defers envelope validation until the block is in fork choice when payload input is seeded from the block body") which uses the same `let emitter!: ChainEventEmitter` + destructuring-assignment + sibling closure capture pattern that #9491 already mitigated in the original failing test below. Same `TS2769` fires at the new test's emit site:

```
test/unit/sync/unknownBlock.test.ts(1027,20): error TS2769: No overload matches this call.
  Argument of type 'ChainEvent.unknownEnvelopeBlockRoot' is not assignable to parameter of type 'unique symbol'.
```

Also, #9479's emit predates this PR's addition of `slot: Slot` to the `ChainEvent.unknownEnvelopeBlockRoot` event signature, so the emit data is missing the required `slot` field after the merge.

## Fix

Same minimal cast workaround as #9491 plus the required `slot: 0` field:

```diff
-      emitter.emit(ChainEvent.unknownEnvelopeBlockRoot, {
+      // tsgo overload-resolution miss when emit is reached through a closure that captures emitter
+      // first; cast re-anchors the StrictEventEmitter overload for ChainEvent keys (see #9491).
+      (emitter as ChainEventEmitter).emit(ChainEvent.unknownEnvelopeBlockRoot, {
         rootHex: blockRootHex,
+        slot: 0,
         peer,
         source: BlockInputSource.gossip,
       });
```

Single-site change. The 5 other `emitter.emit(ChainEvent.unknownEnvelopeBlockRoot, ...)` sites in the file remain unchanged because they aren't reached through a sibling closure capture; the cast at the sibling test's emit (introduced in #9491, currently at line 1126) also remains as-is and continues to typecheck cleanly with the expanded `EventType` union from #9439.

## Test plan

- [ ] CI: `Type Checks (24)` passes (no TS2769 on `unknownBlock.test.ts`).
- [ ] CI: the new `defers envelope validation until the block is in fork choice when payload input is seeded from the block body` test still passes — emit semantics unchanged.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: packages/beacon-node/test/unit/sync/unknownBlock.test.ts [hunk 1]
```diff
@@ -1024,8 +1024,11 @@ describe("UnknownBlockSync", () => {
...
 
-      emitter.emit(ChainEvent.unknownEnvelopeBlockRoot, {
+      // tsgo overload-resolution miss when emit is reached through a closure that captures emitter
+      // first; cast re-anchors the StrictEventEmitter overload for ChainEvent keys (see #9491).
+      (emitter as ChainEventEmitter).emit(ChainEvent.unknownEnvelopeBlockRoot, {
         rootHex: blockRootHex,
+        slot: 0,
         peer,
         source: BlockInputSource.gossip,
       });
```
[the remark this answers is not in the document]
Comment (lodekeeper) [reply packages/beacon-node/test/unit/sync/unknownBlock.test.ts:1034]: Declining both suggestions, but flagging the reasoning:

1. **`tsgo` vs `tsc`** — `tsgo` is correct, not a typo. This repo uses [`@typescript/native-preview`](https://github.com/microsoft/typescript-go) via `"check-types": "tsgo"` in `packages/beacon-node/package.json:94`, with `@typescript/native-preview: 7.0.0-dev.20260303.1` pinned in the root `package.json`. The overload-resolution behavior that motivates this cast is specifically `tsgo`'s — `tsc` doesn't reject this site.

2. **`slot: 0` vs `block.message.slot`** — kept `slot: 0` for consistency with every other `emitter.emit(ChainEvent.unknownEnvelopeBlockRoot, ...)` site in this file (`unknownBlock.test.ts:762`, `:836`, `:926`, `:1131`). The field is a logging/prune hint per the emitter.ts comment (`// slot is the message slot, not necessarily the envelope's slot, but useful as a logging/prune hint`), not a correctness-load-bearing value in these tests, and switching just this one site would diverge from the established pattern. Happy to update all sites to `block.message.slot` in a follow-up if you'd rather have semantic accuracy across the board.

**Comment by lodekeeper** [comment]
Re Gemini's two suggestions on the inline thread: declined both with reasoning in `discussion_r3381092996`. tldr: `tsgo` is correct (this repo uses `@typescript/native-preview` via `"check-types": "tsgo"`, the overload-resolution behavior is tsgo-specific), and `slot: 0` matches the established convention across every other `emitter.emit(ChainEvent.unknownEnvelopeBlockRoot, ...)` site in this test file. Noted on the consumer-version sunset.
